### ISSUE TITLE
Memory Leak - Inventory and Cubimal Windows

### ISSUE THREAD

**Issue by Tatwi** [Tatwi/RocketTux#1]
On the main menu, each time an inventory or cubimal page loads (when clicking either Next or Back), RAM is used and never released, despite the windows being destroyed before each page change. 

- Possible that this.inventoryWindow.destroy(); and this.cubWindow.destroy(); are not deleting all the icons that are created, etc.

**Comment by Tatwi** [comment]
Resloved by creating these windows using a different way. See the following commits,
f56e69104ead06bd373d90396eca1c80db6d5e53
f254bc1be5f3d3e00fa36157ad13d315e3a33399

**Comment by Thrax989** [comment]
what are the best means to contact you these days by email?
